<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 * @var \Magento\Framework\Escaper $escaper
 */

?>
    <li class="my-refund" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <a class="logged-in" data-bind="attr: { href: '<?= $block->getUrl("tasks/sales/ListRequests") ?>' }">
            <?= $escaper->escapeHtml(__('My Refund Requests')) ?>
        </a>
        <!-- /ko -->
    </li>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
    </script>

