<form action="<?= $block->getUrl('tasks/contact/save') ?>" method="post" id="contact-form">
    <?= $block->getBlockHtml('formkey'); ?>
    <div>
        <label for="name">Name:</label>
        <input type="text" id="name" name="name"/>
    </div>
    <div>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required />
    </div>
    <div>
        <label for="phone">Phone Number:</label>
        <input type="text" id="phone" name="phone" required />
    </div>

    <div>
        <label for="message">Message:</label>
        <textarea id="message" name="message" required></textarea>
    </div>

    <div>
        <button type="submit">Submit</button>
    </div>
</form>
